### PR TITLE
feat: update to tree-sitter 0.24

### PR DESCRIPTION
**Pull request by ObserverOfTime**
- Add the new `tree-sitter.json` config file
- Remove existing binding files
- Run `tree-sitter init` to create them anew
   - Manually tweak a few of them
- Run `tree-sitter generate` to update the grammar
- Include `Cargo.lock` in versioning instructions
- Update the main CI workflow
- Introduce a new release workflow

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
There are no changes to `parser.c` this time so the failures likely come from a change in the doc files.

**Comment by clason** [comment]
Could you please not make ALL THE CHANGES in a single PR.

**Comment by ObserverOfTime** [comment]
All the changes, barring CI, come from running 2 commands.

**Comment by clason** [comment]
So that's three separate sets of changes, no?

**Comment by ObserverOfTime** [comment]
You will still have 30 changed files in one of the sets.

**Comment by clason** [comment]
Yes but I can ignore those and not play "hunt the changes that will affect us".

**Pull request closed without merging**
